import Head from "next/head";
import { createClient } from "next-sanity";
import KontaktForm from "@/components/form/kontaktform";

export default function Malerier(omMeg) {
  const bioData = omMeg.omMeg;
  console.log("Fant jeg noe data? ", bioData);
  return (
    <>
      <Head>
        <title>Hei på deg | Marimaleri.no</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {bioData.map((about) => {
          return (
            <div key={about.title} className="about">
              <div className="about__profile">
                <h1 className="about__profile--title">{about.title}</h1>
                <p>bilde av deg kommer, eller hva tenker du?</p>
              </div>
              <div className="about__bio">
                <p className="about__bio--text">{about.ommeg}</p>
              </div>
            </div>
          );
        })}
        <KontaktForm />
      </main>
    </>
  );
}

const client = createClient({
  projectId: "4i1q7pgh",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false,
});

export async function getServerSideProps() {
  const omMeg = await client.fetch(`*[_type == "about"]{title, ommeg}`);

  return {
    props: {
      omMeg,
    },
  };
}
