import { createClient } from "next-sanity";
import Head from "next/head";
import Navbar from "@/components/nav/navbar";
import Image from "next/image";

export default function Post({ post }) {
  console.log("data :", post);
  return (
    <>
      <Head>
        <title>{post.tittel} | Marimaleri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="container">
          <Navbar />
          <div detail>
            <h1>{post.tittel}</h1>
            <Image
              src={post.bilde + "?auto=format"}
              alt="Maleri malt av Mari Tomter"
              width={500}
              height={500}
            />
          </div>
        </div>
      </main>
    </>
  );
}

const client = createClient({
  projectId: "4i1q7pgh",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false,
});

export async function getStaticProps({ params }) {
  const query = `*[_type == "malerier" && slug.current == $slug] {
    _id,
    tittel,
    "bilde": bilde.asset->url,
    'slug': slug.current,
    pris,beskrivelse, size,
  }`;

  const options = { slug: params.slug };

  const post = await client.fetch(query, options);

  return {
    props: { post: post[0] },
  };
}

export async function getStaticPaths() {
  const query = `*[_type == "malerier"]{ 'slug': slug.current }`;

  const posts = await client.fetch(query);

  const paths =
    posts?.map((post) => ({
      params: {
        slug: post.slug,
      },
    })) || [];

  return {
    paths,
    fallback: false,
  };
}
