import Head from "next/head";
import { createClient } from "next-sanity";
import Image from "next/image";
import Link from "next/link";

export default function Malerier(malerier) {
  console.log(malerier.malerier);
  const resultat = malerier.malerier;

  return (
    <>
      <Head>
        <title>Malerier | Marimaleri.no</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>yei</h1>
        <div className="malerier__"></div>
        {resultat.map((sortert, index) => {
          console.log("sortet", sortert.tittel);
          console.log("slug", sortert.slug);

          return (
            <>
              {sortert.publiser ? (
                <Link
                  href={`/malerier/details/[slug]`}
                  as={`/malerier/details/${sortert.slug.current}`}
                  key={index}
                  className="malerier__link"
                >
                  <div className="malerier__bilde">
                    <Image
                      src={sortert.bilde + "?auto=format"}
                      alt="Maleri malt av Mari Tomter"
                      fill={true}
                    />
                  </div>

                  <p className="malerier__tittel">{sortert.tittel}</p>
                  <p className="malerier__pris">kr {sortert.pris},-</p>
                </Link>
              ) : (
                ""
              )}
            </>
          );
        })}
      </main>
    </>
  );
}

const client = createClient({
  projectId: "4i1q7pgh",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false,
});

export async function getServerSideProps() {
  const malerier = await client.fetch(
    `*[_type == "malerier"]{_rev,_id,tittel,slug,publiser, pris,"bilde": bilde.asset->url}`
  );

  return {
    props: {
      malerier,
    },
  };
}

/* export function getAllPostIds(malerier) {
  const filNavn = fs.readdirSync(malerier);

  return filNavn.map((fil) => {
    return {
      params: {
        id: filNavn.replace(/\.md$/, ""),
      },
    };
  });
}
 */
