import Head from "next/head";

import Navbar from "@/components/nav/navbar";

export default function Malerier() {
  return (
    <>
      <Head>
        <title>Spesial bestilling | Marimaleri.no</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <h1>test</h1>
      </main>
    </>
  );
}
