import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import Link from "next/link";
import Heading from "@/components/common/Heading";
import nyheter from "../../public/images/nyheter.jpg";
import malerier from "../../public/images/malerier.jpg";
import flokk from "../../public/images/flokk.jpg";
import familie from "../../public/images/familie.jpg";
/* console.group(nyheter); */

import Navbar from "@/components/nav/navbar";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <section className="card__section">
          <div className="card">
            <Link href="/nyheter/Nyheter">
              <Image
                src={nyheter}
                alt="maleri av Mari Tomter"
                className="card__bilde"
                /*  width={500}
                height={500} */
              />
              <div className="kort-text">Nyheter</div>
            </Link>
          </div>
          <div className="card">
            <Link href="/nyheter/Nyheter">
              <Image
                src={malerier}
                alt="maleri av Mari Tomter"
                className="card__bilde"
                /*  width={500}
                height={500} */
              />
              <div className="kort-text">Malerier</div>
            </Link>
          </div>
          <div className="card">
            <Link href="/nyheter/Nyheter">
              <Image
                src={familie}
                alt="maleri av Mari Tomter"
                className="card__bilde"
                /*  width={500}
                height={500} */
              />
              <div className="kort-text">Familiebilde</div>
            </Link>
          </div>
          <div className="card">
            <Link href="/nyheter/Nyheter">
              <Image
                src={flokk}
                alt="maleri av Mari Tomter"
                className="card__bilde"
                /*  width={500}
                height={500} */
              />
              <div className="kort-text">Flokk</div>
            </Link>
          </div>
        </section>
      </main>
    </>
  );
}
