import Head from "next/head";
import { createClient } from "next-sanity";

export default function Faq(faq) {
  console.log("hentet data", faq.faq);
  const dataFaq = faq.faq;
  return (
    <>
      <Head>
        <title>Galleriet | Marimaleri.no</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section>
          <h1 className="about__profile--title">FAQ</h1>
          {dataFaq.map((faqdata) => {
            return (
              <>
                <div className="about">
                  <h3 className="about__profile--title">{faqdata.tittel}</h3>
                  <p className="about__bio--text">{faqdata.beskrivelse}</p>
                </div>
              </>
            );
          })}
        </section>
      </main>
    </>
  );
}

const client = createClient({
  projectId: "4i1q7pgh",
  dataset: "production",
  apiVersion: "2022-03-25",
  useCdn: false,
});

export async function getServerSideProps() {
  const faq = await client.fetch(`*[_type == "faq"]{tittel, beskrivelse}`);

  return {
    props: {
      faq,
    },
  };
}
